title: Project

status:
  draft:
    label: Draft
    text: This page is in draft mode.
  listed:
    label: Published
    text: This page is online and can be viewed publicly.

create:
  status: listed

options:
  delete: true  # Prevent deletion
  changeSlug: true  # Prevent changing the slug
  changeStatus: true  # Prevent changing the status
  changeTemplate: false  # Prevent changing the template



columns:

  - width: 2/3
    fields:
      media:
        label: Media
        type: files
        help: Add images and super-compressed videos.
        multiple: true
        layout: cards
        size: large
        accept: image/*, video/*
        info: |
          Highlight: {{ file.highlight }} & pair with next: {{ file.isDiptych }}

  - width: 1/3
    sections:
      clientInfo:
        type: fields
        fields:
          hideFromIndex:
            label: Hide from Index
            type: toggle
            default: true
            text: Hide this project from the index
          categories:
            label: Categories
            type: multiselect
            default: ['Featured']
            options:
              type: query
              query: site.projectCategories.toStructure
              text: "{{ item.categoryName }}"
              value: "{{ item.categoryName }}"
      mediaLibrary:
        type: files
        layout: list
        size: small
        headline: Media Library
        