title: Site

columns:
  - width: 1/2
    fields:
      siteDescription:
        label: Site Description
        type: textarea
        help: This is the text that will be displayed in search results.
        size: small
        buttons: false

      siteImage:
        label: Site Image
        type: files
        multiple: false
        help: This image is displayed on social platforms.
        accept: image/jpeg, image/png
        layout: cardlets
        image:
          cover: true


      projectCategories:
        label: Project Categories
        type: structure
        help: Add the project categories here before adding them to projects.
        fields:
          categoryName:
            label: Name
            type: text

      # --- Landing fields (direct children of "fields") ---
      landing_enabled:
        label: Enable landing
        type: toggle
        default: false
        width: 1/2 

      landing_show_once:
        label: Show only once per session
        type: toggle
        default: true
        width: 1/2 

      landing_media:
        label: Landing image or video
        type: files
        multiple: false
        uploads:
          template: default
        help: Select a single image or video
        width: 1/2
      
      landing_logo_color:
        label: Logo colour
        type: select
        options:
         white: White
         black: Black
        default: white
        width: 1/2 
        
      landing_poster:
        label: Landing video poster (optional)
        type: files
        multiple: false
        accept: image/jpeg, image/png, image/webp
        uploads:
          template: default
        help: Custom poster image for the landing video. If not set, will auto-generate from video.
        width: 1/2
      

      # landing_byline:
      #   label: Intro byline
      #   type: text
      #   # width: 1/2
      #   placeholder: e.g. Photographer & Director | People, Sport, Culture   

      # landing_link:
      #   label: Landing click target
      #   type: url
      #   placeholder: /featured
      #   help: Where to go when clicked. Leave empty to just reveal the page.

      customEmbeds:
        label: Custom Embeds
        type: textarea
        size: tiny
        buttons: false
        help: If you want to add custom embeds, popups, stats etc, paste the code here and it will be added to the bottom of the body tag.

  - width: 1/2
    sections:
      pages:
        type: pages
        headline: Pages
        layout: list
        image: false
        template:
          - page
          - about
          - projects

      latestProjects:
        type: pages
        headline: Latest Projects
        parent: site.find("projects")
        layout: list
        limit: 100
        image: false
        image:
          query: page.media.toFiles.first
        template:
          - project